name: test_windows

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
      - '.github/workflows/test_windows.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
      - '.github/workflows/test_windows.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.0
        host: windows
        target: desktop
        arch: win64_msvc2022_64
        dir: ${{ github.workspace }}/Qt
        install-deps: true
        modules:
        archives:
        cache: true
        cache-key-prefix: 'qt6.8.0'
        setup-python: false
        set-env: true

    - name: Configure CMake
      env:
        QT_DIR: ${{ github.workspace }}/Qt/6.8.0/msvc2022_64
      run: |
        cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="$QT_DIR"

    - name: Build
      run: |
        cmake --build build --config Release --verbose

    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure
