name: test_windows

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
      - '.github/workflows/test_windows.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
      - '.github/workflows/test_windows.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        qt_ver: [6.4.3, 6.8.0]
        include:
          - qt_ver: 6.4.3
            qt_arch: win64_msvc2019_64
          - qt_ver: 6.8.0
            qt_arch: win64_msvc2022_64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_ver }}
        host: windows
        target: desktop
        arch: ${{ matrix.qt_arch }}
        dir: ${{ github.workspace }}/Qt
        install-deps: true
        modules:
        archives:
        cache: true
        cache-key-prefix: qt${{ matrix.qt_ver }}_${{ matrix.qt_arch }}
        setup-python: false
        set-env: true

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${{ matrix.qt_ver }}/${{ matrix.qt_arch }}

    - name: Build
      run: |
        cmake --build build --config Release --verbose

    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure
